# Generated by Django 5.0.3 on 2024-03-24 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_alter_fotografia_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='descrição',
            new_name='descricao',
        ),
    ]
